version: "3"
services:
  spring-boot-mysql:
    image: spring-boot-mysql
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - spring-boot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=diary  

networks:
  spring-boot-mysql: 
