version: '3'
services:
  jenkins:
    build:
      context: jenkins
    image: pregatit-docker-jenkins
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
    #  - "$PWD/jenkins/jenkins_configuration:/var/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/local/bin/docker:/usr/local/bin/docker

  demo-app-python:
    build:
      context: .
      dockerfile: Dockerfile
    image: pregatit-demo-app-python
    ports:
     - 5000:5000
    container_name: demo-app-python